output_prefix: a_string  # type "string" (optional)
make_unique: true  # default value of type "boolean".
kmer_size: 31  # default value of type "int".
index_name: a_string  # type "string"
fasta_files:  # array of type "File"
  - class: File
    path: a/file/path
