sjdbScore: 1  # default value of type "int".
quantTranscriptomeBAMcompression: 10  # default value of type "int".
quantMode: ["TranscriptomeSAM", "GeneCounts"]  # array of type "string"
output_dir_name: STAR  # default value of type "string".
outSJfilterReads: "Unique"  # default value of type "string".
outSAMunmapped: "Within"  # default value of type "string".
outSAMtype: ["BAM", "Unsorted"]  # array of type "string"
outSAMstrandField: intronMotif  # default value of type "string".
outSAMattributes: ["NH", "HI", "AS", "NM", "MD"]  # array of type "string"
outFilterType: "BySJout"  # default value of type "string".
outFilterMultimapNmax: 20  # default value of type "int".
outFilterMismatchNoverReadLmax: 0.04  # default value of type "float".
outFilterMismatchNmax: 999  # default value of type "int".
outBAMcompression: 10  # default value of type "int".
nthreads: 0  # type "int"
limitBAMsortRAM: 0  # type "long" (optional)
genomeDir:  # type "Directory"
    class: Directory
    path: a/directory/path
fq:  # array of type "File"
  - class: File
    path: a/file/path
alignSJoverhangMin: 8  # default value of type "int".
alignSJDBoverhangMin: 1  # default value of type "int".
alignMatesGapMax: 1000000  # default value of type "int".
alignIntronMin: 20  # default value of type "int".
alignIntronMax: 1000000  # default value of type "int".
