bam: null
bowtie-chunkmbs: null
bowtie-e: null
bowtie-m: null
bowtie-n: null
bowtie-path: null
bowtie2: null
bowtie2-k: null
bowtie2-mismatch-rate: null
bowtie2-path: null
bowtie2-sensitivity-level: null
calc-ci: null
calc-pme: null
ci-credibility-level: null
ci-memory: null
ci-number-of-samples-per-count-vector: null
downstream_read_file: null
estimate-rspd: null
forward-prob: null
fragment-length-max: null
fragment-length-mean: null
fragment-length-min: null
fragment-length-sd: null
gibbs-burnin: null
gibbs-number-of-samples: null
gibbs-sampling-gap: null
keep-intermediate-files: null
no-bam-output: null
no-qualities: null
num-rspd-bins: null
num-threads: null
output-genome-bam: null
paired-end: null
phred33-quals: null
phred64-quals: null
quiet: null
reference_files:
    class: Directory
    path: default/directory/path
reference_name: default_string
sam: null
sam-header-info: null
sample_name: default_string
sampling-for-bam: null
samtools-sort-mem: null
seed: null
seed-length: null
solexa-quals: null
strand-specific: null
tag: null
temporary-folder: null
time: null
upstream_read_files: null
