star_path:  # type "Directory"
    class: Directory
    path: a/directory/path
star: false  # type "boolean" (optional)
reference_name: a_string  # type "string"
reference_fasta_files:  # type "File"
    class: File
    path: a/file/path
nthreads: 0  # type "int"
gtf:  # type "File"
    class: File
    path: a/file/path
IndexName: a_string  # type "string"
