star: false  # type "boolean" (optional)
reference_name: a_string  # type "string"
reference_fasta_files:  # type "File"
    class: File
    path: a/file/path
gtf:  # type "File"
    class: File
    path: a/file/path
