# Config for CWL implementation of the FastQC tool
# On the left are available inputs to the fastqc.cwl script
# Right of those inputs are brief labels describing their use

### INSTRUCTIONS ###

# To enable a specific input, remove the '#' preceding it
# modify the field with the appropriate value, path, etc

seqfile:                                                        # a set of sequence files
  - class: File
    path: "/data/scratch/nmaki/cwl_testing/0AB1_S1_LALL_R1_001.fastq"

#casava: false                                                  # files come from raw casava output

#nano: false                                                    # files come from nanopore sequences + in fast5 format

#nofilter: false                                                # if running with --casava then don't remove read flagged by casava as poor quality when performing the QC analysis

#extract: false                                                 # the zipped output file will be uncompressed

#java: /update/with/path/to/file                                # the full path to the java binary you want to use to launch fastqc

#noextract: true                                                # do not uncompress the output file

#nogroup: true                                                  # disable grouping of bases for reads >50bp

#min_length: /update/with/int                                   # sets an artificial lower limit on the length of the sequence to be shown in the report

#input_format: /update/with/string                              # bypasses the normal sequence file format detection, forces fastqc to use the specified format: (bam,sam,bam_mapped,sam_mapped and fastq)

nthreads: 8                                                     # the number of files which can be processed simultaneously

#contaminants: /update/with/path/to/file                        # a non-default file which contains the list of contaminants to screen overrepresented sequences against

#adapters: /update/with/path/to/file                            # a non-default file which contains the list of adapter sequences which will be explicity searched against the library

#limits: /update/with/path/to/file                              # a non-default file which contains a set of criteria which will be used to determine the warn/error limits for the various modules

#kmers: /update/with/int                                        # specifies the length of Kmer to look for in the Kmer content module (length must be between 2 and 10. Default length is 7 if not specified)

#quiet: false                                                   # suppress all progress messages on stdout and only report errors

#dir: /update/with/path/to/directory                            # selects a directory to be used for temporary files written when generating report images. Defaults to system temp directory if not specified

output_prefix: jcoffman_006.1490192921.0AB1_S1_LALL_R1_001      # prefix to be added to output files
