output_prefix: a_string  # type "string" for cd-hit-est output prefix

output_dir: a_string  # type "string" for trinity output naming
trinity_ss_lib_type: a_string  # type "string"
seqfile_1:  # type "File"
    class: File
    path: a/file/path
seqfile:  # type "File"
    class: File
    path: a/file/path
