promoter_set: a_string  # type "string"
output_dir:  # type "Directory"
    class: Directory
    path: a/directory/path
input_list:  # type "File"
    class: File
    path: a/file/path
find_motif_loc:  # type "File"
    class: File
    path: a/file/path
cpu: 0  # type "int"
